#!/bin/bash
EXEC_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# INPUT_DEVICE="/dev/input/event1" # VOLUME KEYS EVENT FILE
# VOLUME_DOWN=114 #0x0072
# VOLUME_UP=115   #0x0073
# BLANK_EVENT="sendevent $INPUT_DEVICE 0 0 0"
#
# INST_DN="sendevent $INPUT_DEVICE 1 $VOLUME_DOWN 1 && $BLANK_EVENT && sendevent $INPUT_DEVICE 1 $VOLUME_UP 1 && $BLANK_EVENT"
# INST_UP="sendevent $INPUT_DEVICE 1 $VOLUME_DOWN 0 && $BLANK_EVENT && sendevent $INPUT_DEVICE 1 $VOLUME_UP 0 && $BLANK_EVENT"
#
# adb -s "$DEVICE" shell "$INST_DN"
# sleep 3
# adb -s "$DEVICE" shell "$INST_UP"

adb shell sendevent /dev/input/event1 1 116 1
adb shell sendevent /dev/input/event1 0 0 0
adb shell sendevent /dev/input/event1 1 116 0
adb shell sendevent /dev/input/event1 0 0 0

#adb shell "input keyevent $ALT_KEY & input keyevent $RIGHT_KEY"
