#!/bin/sh
EXEC_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $EXEC_DIR/utils
USAGE="bluetooth [-e|-d] [-s device]"

ENABLE=true #default
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -e) ENABLE=true ;;
        -d) ENABLE=false ;;
        -s|--device) DEVICE="$2"; shift ;;
        -h|--help) echo $USAGE; exit 0 ;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

DEVICE=$(getDevice)

if [ "$ENABLE" = true ]; then
  adb -s "$DEVICE" shell service call bluetooth_manager 6
else
  adb -s "$DEVICE" shell service call bluetooth_manager 8
fi
