#!/bin/bash
EXEC_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $EXEC_DIR/utils
USAGE="darkMode [-s device] [-e|-d]"
#defaults
TOGGLE=true
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -e) ENABLE=true;TOGGLE=false ;;
        -d) ENABLE=false;TOGGLE=false ;;
        -s|--device) DEVICE="$2"; shift ;;
        -h|--help) echo $USAGE; exit 0 ;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

DEVICE=$(getDevice)

VALUE_OFF="1"
VALUE_ON="2"

if [ "$TOGGLE" = true ]; then
  STATUS=$(adb -s "$DEVICE" shell settings get secure ui_night_mode)
  echo "  ~~> CURRENT STATUS: [$STATUS]"
  if [ "$STATUS" = "$VALUE_OFF" ]; then
    echo "    |--> ENABLING [$VALUE_ON]"
    ENABLE=true
  else
    ENABLE=false
    echo "    |--> DISABLING [$VALUE_OFF]"
  fi
fi

if [ "$ENABLE" = true ]; then
  VALUE=$VALUE_ON
else
  VALUE=$VALUE_OFF
fi

adb -s "$DEVICE" shell settings put secure ui_night_mode $VALUE
# adb -s "$DEVICE" reboot
