#!/bin/bash
EXEC_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $EXEC_DIR/utils

USAGE="midOf -e ELEMENT_NAME [-s DEVICE] [-f|-x XML_RESOURCE]"
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -f|--file) XMLFILE="$2"; shift ;;
        -x|--xml) XML="$2"; shift ;;
        -e|--element) ELEMENT="$2"; shift ;;
        -s|--device) DEVICE="$2"; shift ;;
        -h|--help) echo $USAGE; exit 0 ;;
        *) echo "Unknown parameter passed: $1. Usage: $USAGE"; exit 1 ;;
    esac
    shift
done

DEVICE=$(getDevice)

if [ -z "$ELEMENT" ]; then
  echo "~~ No element given, use -e [ELEMENT NAME] ~~"
  exit -1
fi

if [ -z "$XML" ]; then
  if [ -z "$XMLFILE" ]; then
    XML=$(sh $EXEC_DIR/fetchUI -s $DEVICE)
  else
    XML=$(cat $XMLFILE)
  fi
fi

BOUNDS=$(echo "$XML" | grep "$ELEMENT" | sed 's/^.*bounds="//' | cut -f1 -d"\"")

IFS='][' read -ra ADDR <<< "$BOUNDS"
IFS=',' read -ra ST <<< "${ADDR[1]}"
IFS=',' read -ra EN <<< "${ADDR[3]}"
MIDX=$((${ST[0]} + ((${EN[0]} - ${ST[0]}) / 2)))
MIDY=$((${ST[1]} + ((${EN[1]} - ${ST[1]}) / 2)))

echo "$MIDX $MIDY"
