#!/bin/bash
EXEC_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $EXEC_DIR/utils
USAGE="recordOn [-s device]"
#defaults
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -s|--device) DEVICE="$2"; shift ;;
        -h|--help) echo $USAGE; exit 0 ;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

DATE=$(date '+%y-%m-%d_%H-%M')
TEMP_DIR=${TMPDIR}
RECORING_FILE="${TEMP_DIR}recording.mp4"
PROCESS_ID="${TEMP_DIR}processId"
rm -f $RECORING_FILE
rm -f $PROCESS_ID

DEVICE=$(getDevice)

scrcpy -s "$DEVICE" -Nr "$RECORING_FILE" & ID=$!
echo "${ID}" > $PROCESS_ID

echo "RECORDING TO [${RECORING_FILE}]"
