#!/bin/sh
EXEC_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $EXEC_DIR/utils
USAGE="restartApp [-a PACKAGE] [-s device]"

ENABLE=true #default
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -a|--app|--package) APP="$2"; shift ;;
        -s|--device) DEVICE="$2"; shift ;;
        -h|--help) echo $USAGE; exit 0 ;;
        *) echo "Unknown parameter passed: $1. Usage: $USAGE"; exit 1 ;;
    esac
    shift
done

DEVICE=$(getDevice)

if [ -z "$APP" ]; then
  echo "No Application package defined: $USAGE"
else
  adb -s $DEVICE shell am force-stop $APP
  adb -s $DEVICE shell monkey -p $APP -c android.intent.category.LAUNCHER 1
fi
