#!/bin/bash
EXEC_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
USAGE="runOnAll -c \"COMMAND\""
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -c|--command) COMMAND="$2"; shift ;;
        -h|--help) echo $USAGE; exit 0;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

adb devices | sed -n '1!p' | while read -r line ; do
  if [[ ! -z $line ]]; then
    device=$(echo $line| cut -d " " -f1)
    echo "   $COMMAND -s $device"
    sh $COMMAND -s $device
    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
  fi
done
