#!/bin/sh
EXEC_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $EXEC_DIR/utils
USAGE="screenshot -n NAME [-d device]"

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -n|--name) NAME="$2"; shift ;;
        -d|--device) DEVICE="$2"; shift ;;
        -h|--help) echo $USAGE; exit 0 ;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

DEVICE=$(getDevice)

adb -s $DEVICE shell screencap -p /sdcard/$NAME.png
adb -s $DEVICE pull /sdcard/$NAME.png
adb -s $DEVICE shell rm /sdcard/$NAME.png
