#!/bin/bash
EXEC_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $EXEC_DIR/utils
USAGE="showTap [-e|-d] [-s device]"

ENABLE=false #default
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -e) ENABLE=true ;;
        -d) ENABLE=false ;;
        -s|--device) DEVICE="$2"; shift ;;
        -h|--help) echo $USAGE; exit 0 ;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

DEVICE=$(getDevice)

if [ "$ENABLE" = true ]; then
  adb -s "$DEVICE" shell content insert --uri content://settings/system --bind name:s:show_touches --bind value:i:1
else
  adb -s "$DEVICE" shell content insert --uri content://settings/system --bind name:s:show_touches --bind value:i:0
fi
