#!/bin/bash
EXEC_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $EXEC_DIR/utils
USAGE="talkback [-s device] [-e|-d|-o]"
# talkback code: https://github.com/google/talkback
#defaults
TOGGLE=true
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -e) ENABLE=true;TOGGLE=false ;;
        -d) ENABLE=false;TOGGLE=false ;;
        -o) OPTION=true;TOGGLE=false ;;
        -s|--device) DEVICE="$2"; shift ;;
        -h|--help) echo $USAGE; exit 0 ;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

DEVICE=$(getDevice)

VALUE_OFF="com.android.talkback/com.google.android.marvin.talkback.TalkBackService"
TALKBACK="com.google.android.marvin.talkback/com.google.android.marvin.talkback.TalkBackService"
ALLYSERVICE="com.balsdon.AccessibilityDeveloperService/.AccessibilityDeveloperService"
VALUE_ON="$TALKBACK:$ALLYSERVICE"

if [ "$TOGGLE" = true ]; then
  STATUS=$(adb -s "$DEVICE" shell settings get secure enabled_accessibility_services)
  if [ "$STATUS" = "$VALUE_OFF" ]; then
    ENABLE=true
  else
    ENABLE=false
  fi
fi

if [ "$OPTION" = true ]; then
  adb -s "$DEVICE" shell am start -n com.google.android.marvin.talkback/com.android.talkback.TalkBackPreferencesActivity
  exit 0
fi

if [ "$ENABLE" = true ]; then
  adb -s "$DEVICE" shell settings put secure enabled_accessibility_services $VALUE_ON
else
  adb -s "$DEVICE" shell settings put secure enabled_accessibility_services $VALUE_OFF
fi
