#!/bin/sh
EXEC_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $EXEC_DIR/utils

USAGE="tap -e ELEMENT_NAME [-s DEVICE] [-f|-x XML_RESOURCE] "
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -f|--file) XMLFILE="$2"; shift ;;
        -x|--xml) XML="$2"; shift ;;
        -e|--element) ELEMENT="$2"; shift ;;
        -s|--device) DEVICE="$2"; shift ;;
        -h|--help) echo $USAGE; exit 0 ;;
        *) echo "Unknown parameter passed: $1. Usage: $USAGE"; exit 1 ;;
    esac
    shift
done

DEVICE=$(getDevice)

if [ -z "$ELEMENT" ]; then
  echo "~~ No element given. Usage: $USAGE ~~"
  exit -1
fi

POS=$(sh midOf -e "$ELEMENT")
adb -s $DEVICE shell input tap $POS
