name: Run Python Test Script (main)
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Run Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Execute Python Unit Test Script [./python/tests/server_test.sh]
        run: ./python/tests/server_test.sh
